/* eslint-disable @next/next/no-img-element */
import { type NextPage } from "next";
import Head from "next/head";
import { Outfit } from "@next/font/google";

const outfit = Outfit({ subsets: ["latin"] });

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Frontend Mentor | NFT Preview Card Component</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <main
        className={`${outfit.className} flex min-h-screen flex-col items-center justify-center bg-[#0d192b]`}
      >
        <div className="w-10/12 rounded-xl bg-[#14253d] p-6 md:w-1/4">
          <img
            src="/images/image-equilibrium.jpg"
            alt="image equilibrium"
            className="rounded-xl"
          />
          <h1 className="mt-8 mb-4 text-2xl font-bold text-white">
            Equilibrium #3429
          </h1>
          <p className="mb-4 text-[#8bacda]">
            Our Equilibrium collection promotes balance and calm.
          </p>
          <div className="flex flex-row place-content-between">
            <div className="flex flex-row items-center font-bold text-[#00fff7]">
              <svg
                width="11"
                height="18"
                xmlns="http://www.w3.org/2000/svg"
                className="mr-1"
              >
                <path
                  d="M11 10.216 5.5 18 0 10.216l5.5 3.263 5.5-3.262ZM5.5 0l5.496 9.169L5.5 12.43 0 9.17 5.5 0Z"
                  fill="#00FFF8"
                />
              </svg>
              0.041 ETH
            </div>
            <div className="flex flex-row items-center text-[#8bacda]">
              <svg
                width="17"
                height="17"
                xmlns="http://www.w3.org/2000/svg"
                className="mr-1"
              >
                <path
                  d="M8.305 2.007a6.667 6.667 0 1 0 0 13.334 6.667 6.667 0 0 0 0-13.334Zm2.667 7.334H8.305a.667.667 0 0 1-.667-.667V6.007a.667.667 0 0 1 1.334 0v2h2a.667.667 0 0 1 0 1.334Z"
                  fill="#8BACD9"
                />
              </svg>
              3 days left
            </div>
          </div>
          <hr className="my-4 h-px border-0 bg-[#2f415b]" />
          <div className="flex flex-row items-center">
            <img
              src="/images/image-avatar.png"
              alt="avatar"
              className="h-10 w-10 rounded-full ring-1 ring-white"
            />
            <span className="ml-5 text-[#8bacda]">
              Creation of{" "}
              <a href="https://frontendmentor.io" className="text-white">
                Jules Wyvern
              </a>
            </span>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
